### ISSUE TITLE
Convention for minor mode keybinding prefix default

### ISSUE THREAD

**Issue by greghendershott** [countvajhula/mindstream#12]
Small point, but maybe easier to change sooner than later:

https://github.com/countvajhula/mindstream/blob/3184aa349d21b7566c28184eeba77833b1b825f9/mindstream.el#L46-L48

Strictly speaking a minor mode isn't supposed to use keybindings like <kbd>C-c C-c</kbd> -- according to [24.3.2 Keymaps and Minor Modes](https://www.gnu.org/software/emacs/manual/html_node/elisp/Keymaps-and-Minor-Modes.html).

> Minor modes may bind commands to key sequences consisting of C-c followed by a punctuation character. However, sequences consisting of C-c followed by one of {}<>:;, or a control character or digit, are reserved for major modes. Also, C-c letter is reserved for users. See [Key Binding Conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html).

This is just the convention for default, "out of box" bindings. Of course any given user can bind differently. (You can even suggest they might want to change the "correct" defaults to something "incorrect". :smile: I think the idea is just to minimize conflicts by default, and leave it up to the user?)

**Comment by countvajhula** [comment]
Thank you for pointing that out. I kind of assumed that `C-c <anything-except-a-letter>` was fair game!

From exhaustively trying out keys, I think this leaves us:

```
C-c ,
C-c '
C-c [
C-c ]
```
... and some other more inaccessible symbols on the number line.

I also don't see `C-,` `C-;` and `C-'` bound. It's weird that we never think of these prefixes...

Any reason not to use `C-;`?

**Comment by greghendershott** [comment]
> I also don't see `C-,` `C-;` and `C-'` bound. It's weird that we never think of these prefixes...
> 
> Any reason not to use `C-;`?

IIUC I think the reason is just that first sentence says to use C-c.

> Minor modes may bind commands to key sequences consisting of C-c followed by a punctuation character.

---

What some minor modes do is define a "dispatch keymap" that has just the suffix keys => comands -- and tell the user to bind a prefix key to that keymap. (A keybinding can be to a command, or to a keymap.)

---

Having said all this, maybe it's a lower priority item to work on...

**Comment by countvajhula** [comment]
Ah whoops, reading fail. I've made the change to use `C-c ,` 🤷
