### ISSUE TITLE
Extensions => modes and modes => templates

### ISSUE THREAD

**Issue by greghendershott** [countvajhula/mindstream#13]
https://github.com/countvajhula/mindstream/blob/3184aa349d21b7566c28184eeba77833b1b825f9/mindstream-session.el#L157-L167

Here I think you could use `auto-mode-alist`?

And probably won't ever need a customization variable of your own?

---

https://github.com/countvajhula/mindstream/blob/3184aa349d21b7566c28184eeba77833b1b825f9/mindstream-session.el#L146-L155

Having got the `(major-mode . extension-regexp)` pair from `auto-mode-alist`, you could _almost_ get away with making a default template name from those. But I guess it's trickier. 1. It's an extension _regexp_. 2. In some cases the major-mode name isn't the prefer file base name (e.g. `emacs-lisp-mode` vs. `elisp.el`).

So I guess even if you could work that for an OK-ish default, you'd probably still want this `cond` (or someday a customization variable) as an override.

**Comment by countvajhula** [comment]
Okay, I _think_ this should be working as you've described above. For the major mode to template mapping, it now just searches the templates folder for any files matching any extension recognizable to the major mode, and picks the first one it finds. This should work as a reasonable default, but if the user has templates like `racket.rkt` and `qi.rkt`, because the latter comes alphabetically before `racket.rkt`, it would always get pulled up as the default anonymous session for Racket Mode buffers via `mindstream-enter-session`. So I added the customization variable to allow the user to override that, and I think that covers all the cases. Wdyt?

**Comment by greghendershott** [comment]
That seems good! Although I don't 100% follow all the details, I think I understand the flow. The usage of `auto-mode-alist` looks right to me.

(As a user, I don't know if I'd want to _customize_ the template to use. If there's more than one suitable, maybe I'd prefer it just ask me. Using `read-file-name`, probably, since most completion systems work nicely with that. So I can probably just type a character or two of the name, hit RET, and voila.)

**Comment by greghendershott** [comment]
p.s. Another benefit to `read-file-name` is the user can press <kbd>M-p</kbd> for history. And if they enable `savehist-mode` in their init file, then this will be persisted. As a result, if the user chooses say `qi.rkt` instead of `racket.rkt`, they can quickly get that. And so you get the benefit of a persisted customization, just from the user choosing this, not needing to customize it explicitly.

**Comment by greghendershott** [comment]
p.p.s. And as long as the `PREDICATE` function is limiting choices to things in the template directory, and with the desired extension, the choices will be a useful subset of all file name history. I am pretty sure the history will be limited as well.

**Comment by countvajhula** [comment]
Yes, it does use `read-file-name` in starting a new session (`mindstream-new`)! The inference only happens in `mindstream-enter-session` which is supposed to put you in the "relevant" session _stat_, [without asking any questions](https://github.com/countvajhula/mindstream?tab=readme-ov-file#entering-sessions-even-more-quickly) 😄 The typical use of `new` would be starting a session from anywhere, in any major mode. The typical use of `enter-session` is if you're in a Racket/ELisp/Markdown/... buffer and want to try things out related to what you're already working on. `enter-session` also doesn't create a new session if there is already one in progress.

Did not know about `M-p`, which sounds like it should work with `mindstream-new`, but right now it's picking a file that isn't even one of the templates, just a recently opened file I think? Another odd thing is that `mindstream-new` features the current file (i.e. the current Emacs buffer, not a template) at the very top of the selection list above `.` and `..`, which I don't think it was doing formerly. I'll debug this and then try again with `savehist-mode` and `M-p` [**edit**: just saw that your most recent comment likely addresses this - will take a look!].

**Comment by countvajhula** [comment]
I'm having trouble coming up with a good predicate. This was my first attempt:

```
(lambda (f)
  (message "dir is %s" (file-name-directory f))
  (equal (file-name-directory f)
         mindstream-template-path))
```

... which didn't show any templates in the selection menu and the output was:
```
dir is nil [5 times]
dir is ../
dir is ./
```

Just an update. Will poke at it more later!

**Comment by countvajhula** [comment]
This predicate shows the contents of the template folder correctly, as before:
```
(lambda (f)
  (member f (directory-files mindstream-template-path)))
```
... but unfortunately `M-p` is able to insert any recent file here and it isn't filtered by the predicate (I tried it with `savehist` mode but I have been using `prescient` for the same thing I believe). Might there be a way to prevent this? As it stands, the behavior is the same here as without the predicate.

**Comment by greghendershott** [comment]
Oh! I'm sorry that turned out to be wrong.

[Although there's definitely a way to make this work as desired (e.g. through using `completing-read` directly instead of the `read-file-name` wrapper) I doubt you want to get into those weeds now, or ever. Instead maybe I could submit a PR.]

**Comment by countvajhula** [comment]
All good, thank you for the valuable suggestions! And nice to know about the relationship between `read-file-name` and `completing-read` as well.
