### ISSUE TITLE
`mindstream-new` outputs "No such file or directory" if you don't have `anon` folder

### ISSUE THREAD

**Issue by nobiot** [countvajhula/mindstream#17]
I follow the [Usage section of REAMDE](https://github.com/countvajhula/mindstream?tab=readme-ov-file#usage). 

>    1. Run mindstream-new (default: C-c , n) to start a session.
>    2. Write!

`C-c , n` gives me the following error.

`mindstream-path` is set to `"/home/nobiot/src/emacs-min-config/mindstream/anon"`. 

```
mindstream--execute-shell-command: Setting current directory: No such file or directory, /home/nobiot/src/emacs-min-config/mindstream/anon/2024-05-07-3aed133ea8349839f78bf499f893dec25d98782e/
```
The session does not start.

If I have created the `anon` directory before calling `C-c , n`, the session starts as expected.

It looks like mindstream-new does not create `anon` directory and expects it to be already present in the system.

**Comment by countvajhula** [comment]
Thank you for the bug report and the analysis! It should be fixed now.
