### ISSUE TITLE
Background saves do not create commits

### ISSUE THREAD

**Issue by countvajhula** [countvajhula/mindstream#29]
_Originally posted by @dasoju in https://github.com/countvajhula/mindstream/issues/27#issuecomment-2266305593_

> I observed one more issue.
> I use super-save-mode, this saves the buffer in background when either
> emacs is idle or switch to another buffer or emacs is out of focus.
> I thought mindstream will do a git commit whever there is a save, but for
> saves triggered by supersave-mode, i don't see any commits
> 
> I see you have live-mode, but looks like i need to enter live mode whenever
> open mindstream.org file, which i don't think i will do, i expect all the
> backups to happen in the background without remembering to do so
> 
> How do i enable git commits even during background saves ?
> Perhaps I am missing something which has already been implemented
> 
> -Kiran
>

**Comment by countvajhula** [comment]
Hi @dasoju, fixed! Looks like `super-save` was using a low-level utility to save the buffer, `basic-save-buffer`. I've changed Mindstream's default trigger to use this since it's called from `save-buffer` as well, and should capture more cases of the buffer being saved.

I'm not sure if there is a reason to favor using `basic-save-buffer` over `save-buffer` in Mindstream's internal operations, as `super-save` does. Currently it uses the latter. There haven't been any problems so I don't see a reason to change it, even though I'm curious why `super-save` uses `basic-save-buffer` instead of `save-buffer`. Perhaps this avoids triggering user advice or hooks or something. I've left a note as a code comment to investigate that further down the road.

**Comment by dasoju** [comment]
okay, i tested it and works now !!
Thanks !

**Comment by dasoju** [comment]
i see one more issue.
I am seeing some slowdown of emacs, while I am working in a org document (interestingly not on mindstream document)
I started the profiler (profiler-start) and i see (profiler-report) that 16% of the memory is being taken by **mindstream-implicitly-iterate-advice**
Is this something that can be fixed in mindstream ?

Please see the snapshot below 
![image](https://github.com/user-attachments/assets/1609efd1-1aad-44ce-8128-7c303d91d803)

**Comment by countvajhula** [comment]
@dasoju Interesting. Looking at `mindstream-implicitly-iterate-advice`, I don't see anything obvious that would cause a performance issue (e.g. it doesn't loop through anything, and it doesn't do any I/O -- i.e. `git commit` -- unless the buffer is actually in a mindstream session, which isn't the case here). Could you try disabling Mindstream and seeing if the performance issue persists? What does the profile look like without Mindstream in the picture?

Also, I see that you are profiling memory usage. Is there a way to get CPU usage as well? That would give us more clues.

**Comment by dasoju** [comment]
I debbugged further, I wanted to keep my undo information across sessions hence using undo-fu-session package.
This is taking most of the memory and CPU time, below is the snapshot 

![image](https://github.com/user-attachments/assets/a3290cb0-9a81-4026-bd03-011bd2187915)

**Comment by countvajhula** [comment]
@dasoju The way we implement the `mindstream-implicitly-iterate-advice` function is to first invoke the function being advised (in this case that's `basic-save-buffer`), and then do any mindstream-specific things. This is the standard way to do it [when using `:around` style advice](https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html). So while `mindstream-implicitly-iterate-advice` is in the stack trace, my guess is that the real issue is in the invocation of `basic-save-buffer`, and it appears that as part of that call, undo-fu is taking up high CPU for some reason. 

Have you tried without mindstream enabled? That would validate if it is unrelated to mindstream (as I suspect).

**Comment by countvajhula** [comment]
I also realized that we don't need to use `:around` style advice there and `:after` is sufficient. I've made this change ([pushed to main](https://github.com/countvajhula/mindstream/commit/9059368337efea723b4141415a0e3c1893ccc8a6)). I don't expect this to fix your issue, but it may make the stack trace more clear. Once you run your tests with and without mindstream enabled, we will know more.
